# Generated by Django 5.1.5 on 2025-03-17 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_permanent_address_userprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserDetails',
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Details'},
        ),
    ]
