# Generated by Django 5.1.5 on 2025-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
