# Generated by Django 5.1.5 on 2025-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_details',
            field=models.JSONField(default=dict),
        ),
    ]
