# Generated by Django 5.1.5 on 2025-03-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_booking_room_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
