# Generated by Django 5.1.5 on 2025-03-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
