# Generated by Django 5.1.5 on 2025-03-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_room_total_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='num_rooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
