# Generated by Django 5.1.5 on 2025-03-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='permanent_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='present_address',
        ),
    ]
