# Generated by Django 5.1.5 on 2025-03-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_userprofile_userdetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Details', 'verbose_name_plural': 'User Details'},
        ),
    ]
