# Generated by Django 5.1.5 on 2025-03-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_booking_created_at_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
