# Generated by Django 5.1.5 on 2025-03-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_room_total_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_rooms',
        ),
    ]
