# Generated by Django 5.1.5 on 2025-03-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_room_total_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='num_rooms',
            new_name='total_rooms',
        ),
    ]
