# Generated by Django 5.1.5 on 2025-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_room_total_rooms_room_num_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='num_rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
